# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  eclilarwebapi:
    image: eclilarwebapi
    build:
      context: .
      dockerfile: Eclilar.WebApi/Dockerfile
    ports:
      - 30001:30001
